%token TOKEN_THING

%{
#include <stuff>

/*
Clunky: Manually declare the interface to the scanner generated by flex. 
*/
extern char *yytext;
extern int yylex();
extern int yyerror( char *str );

/*
Clunky: Keep the final result of the parse in a global variable,
so that it can be retrieved by main().
*/
double parser_result = 0.0;
%}

%%

program: thing
		{do this;}
	;

%%

int yyerror(char *str) {
	printf("parse error: %s\n",str);
}
