#ifndef lint
static const char yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#include <stdlib.h>
#include <string.h>

#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define YYPATCH 20070509

#define YYEMPTY (-1)
#define yyclearin    (yychar = YYEMPTY)
#define yyerrok      (yyerrflag = 0)
#define YYRECOVERING (yyerrflag != 0)

extern int yyparse(void);

static int yygrowstack(void);
#define YYPREFIX "yy"
#line 47 "parser.y"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "decl.h"
#include "stmt.h"
#include "expr.h"
#include "type.h"
#include "param_list.h"
#include "symbol.h"
/*
Clunky: Manually declare the interface to the scanner generated by flex. 
*/
extern char *yytext;
extern int yylex();
extern int yyerror( char *str );

/*
Clunky: Keep the final result of the parse in a global variable,
so that it can be retrieved by main().
*/
struct decl *parser_result = 0;
#line 70 "parser.y"
typedef union {
	struct decl *decl;
	struct expr *expr;
	struct stmt *stmt;
	struct type *type;
	struct param_list *param_list;
	char *name;
	int integer;
} YYSTYPE;
#line 55 "parser.tab.c"
#define TOKEN_PRINT 257
#define TOKEN_FUNCTION 258
#define TOKEN_FOR 259
#define TOKEN_IF 260
#define TOKEN_ELSE 261
#define TOKEN_RETURN 262
#define TOKEN_LEFT_BRACE 263
#define TOKEN_RIGHT_BRACE 264
#define TOKEN_LEFT_PAREN 265
#define TOKEN_RIGHT_PAREN 266
#define TOKEN_LEFT_BRACKET 267
#define TOKEN_RIGHT_BRACKET 268
#define TOKEN_STRING 269
#define TOKEN_INTEGER 270
#define TOKEN_CHAR 271
#define TOKEN_VOID 272
#define TOKEN_BOOLEAN 273
#define TOKEN_ARRAY 274
#define TOKEN_GE 275
#define TOKEN_LE 276
#define TOKEN_EQ 277
#define TOKEN_NE 278
#define TOKEN_LT 279
#define TOKEN_GT 280
#define TOKEN_AND 281
#define TOKEN_OR 282
#define TOKEN_NOT 283
#define TOKEN_INCREMENT 284
#define TOKEN_DECREMENT 285
#define TOKEN_ADD 286
#define TOKEN_SUBTRACT 287
#define TOKEN_MULTIPLY 288
#define TOKEN_DIVIDE 289
#define TOKEN_MODULUS 290
#define TOKEN_EXPONENTIATE 291
#define TOKEN_ASSIGN 292
#define TOKEN_COMMA 293
#define TOKEN_COLON 294
#define TOKEN_SEMICOLON 295
#define TOKEN_TRUE 296
#define TOKEN_FALSE 297
#define TOKEN_CHAR_LITERAL 298
#define TOKEN_INTEGER_LITERAL 299
#define TOKEN_STRING_LITERAL 300
#define TOKEN_IDENTIFIER 301
#define YYERRCODE 256
short yylhs[] = {                                        -1,
    0,    1,    1,    2,    2,    2,   14,   14,   16,   16,
   16,   16,   16,   16,   16,   15,   15,   15,   17,   17,
   18,   18,    3,    3,    3,    4,    4,    4,    4,    4,
    4,    4,    5,    5,    5,    6,    6,    6,    6,    7,
    7,    8,    8,    8,    9,    9,    9,   10,   10,   11,
   11,   12,   12,   13,   13,   13,   13,   13,   13,   13,
   13,   13,   19,   19,   19,   19,   19,   19,   19,   20,
   20,   21,   21,   22,   33,   67,   34,   37,   38,   32,
   30,   31,   35,   36,   65,   66,   61,   59,   62,   60,
   63,   64,   43,   45,   46,   41,   44,   42,   39,   40,
   53,   54,   55,   47,   48,   49,   50,   51,   52,   28,
   56,   27,   29,   57,   58,   26,   25,   24,   23,
};
short yylen[] = {                                         2,
    1,    2,    1,    6,    4,    7,    1,    1,    1,    2,
    3,    3,    9,    7,    3,    5,    7,    9,    1,    0,
    2,    1,    3,    3,    1,    3,    3,    3,    3,    3,
    3,    1,    3,    3,    1,    3,    3,    3,    1,    3,
    1,    2,    2,    1,    2,    2,    1,    1,    0,    1,
    0,    3,    1,    1,    4,    1,    1,    1,    1,    1,
    3,    3,    1,    1,    1,    1,    1,    5,    5,    1,
    0,    1,    3,    3,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,
};
short yydefred[] = {                                      0,
  119,    0,    1,    0,    0,    2,  112,    0,   76,   87,
   88,   89,   90,   91,   92,    0,   63,   64,   65,   66,
   67,    0,    0,  110,  113,    0,    5,   85,    0,    0,
   81,   83,  101,  105,  114,  115,  116,  117,  118,    0,
   25,    0,    0,   39,    0,   44,    0,    0,   57,   56,
   58,    0,    0,    0,    0,   59,   60,    0,    0,    0,
    0,   99,  100,    4,    0,    0,   93,   94,   95,   96,
   97,   98,  104,    0,    0,    0,    0,    0,    0,    0,
    0,  106,  107,  108,    0,    0,    0,  109,    0,  102,
  103,   45,   46,    0,   75,   77,   78,   80,    9,    0,
    0,    0,    7,    8,    0,   19,    0,    0,    0,    0,
    0,    0,    0,   42,   43,   86,    0,    0,    0,    0,
   70,    0,   23,   24,    0,    0,    0,    0,    0,    0,
    0,    0,   36,   37,   38,   40,    0,   50,  111,   10,
    0,   82,   62,    0,   21,    6,    0,    0,    0,    0,
    0,   84,   61,   68,    0,   69,    0,   55,   52,   15,
   11,   12,    0,    0,   74,   73,    0,    0,    0,   16,
    0,    0,   79,    0,    0,   17,   14,    0,   18,   13,
};
short yydgoto[] = {                                       2,
    3,   99,   58,   41,   42,   43,   44,   45,   46,   59,
  137,  101,   47,  102,  103,  104,  105,  106,  119,  120,
  121,  122,   48,   49,   50,   51,    8,   26,  140,   60,
  143,  109,  110,  111,   53,  153,  112,  174,   65,   66,
   74,   75,   76,   77,   78,   79,   80,   54,   85,   86,
   87,   89,   55,   92,   93,  141,   56,   57,   17,   18,
   19,   20,   21,   22,   29,  117,   23,
};
short yysindex[] = {                                   -274,
    0,    0,    0, -274, -257,    0,    0,  -64,    0,    0,
    0,    0,    0,    0,    0, -260,    0,    0,    0,    0,
    0, -233,  -64,    0,    0, -224,    0,    0, -224, -214,
    0,    0,    0,    0,    0,    0,    0,    0,    0, -227,
    0, -141, -209,    0, -234,    0, -160, -214,    0,    0,
    0,  -70, -224, -178, -178,    0,    0, -111, -202, -224,
  -64,    0,    0,    0, -224, -224,    0,    0,    0,    0,
    0,    0,    0, -224, -224, -224, -224, -224, -224, -224,
 -224,    0,    0,    0, -224, -224, -224,    0, -224,    0,
    0,    0,    0, -224,    0,    0,    0,    0,    0, -235,
 -195,  -70,    0,    0, -195,    0, -254,  -70, -224, -224,
 -214, -214, -217,    0,    0,    0,  -64, -183, -257, -184,
    0, -222,    0,    0, -119, -119, -119, -119, -119, -119,
 -209, -209,    0,    0,    0,    0, -184,    0,    0,    0,
 -224,    0,    0, -227,    0,    0, -195, -207, -207, -224,
 -224,    0,    0,    0, -274,    0,  -64,    0,    0,    0,
    0,    0, -207, -217,    0,    0, -224,  -70, -207,    0,
 -171, -224,    0,  -70, -184,    0,    0,  -70,    0,    0,
};
short yyrindex[] = {                                      0,
    0,    0,    0,  100,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0, -161,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0, -251,   62,    0,   34,    0,  -15,  -43,    0,    0,
    0, -150,    0,    0,    0,    0,    0, -247,    0,    0,
 -135,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0, -125,    0,    0,    0,    0,    0, -148,
    0, -121,    0,    0,    0,    0,    6, -150, -144, -138,
    0,    0,    0,    0,    0,    0,    0, -252,    0,    0,
    0, -104,    0,    0, -153,  134,  140,  143,  162,  181,
   86,  110,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0, -144,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0, -144,    0,    0,    0,
  -99,  -92,    0,    0,    0,    0,    0,    0,    0,    0,
};
short yygindex[] = {                                      0,
  174,  126,  -24,  107,  180,   96,   19,    0,  127, -105,
   70,  -85,    0,   15,  -26, -152,   77,   84,   -5,    0,
   39,    0,    1,    0,    0,    0,   72,    0,  -16,  -19,
  -95,    0,    0,    0,  -10, -114,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,  -34,    0,    0,
    0,    0,    0,    0,    0,   81,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,
};
#define YYTABLESIZE 476
short yytable[] = {                                      27,
    5,   40,   16,  148,    5,  156,   52,   81,  138,  146,
   32,   53,   32,   53,   32,  171,   32,   30,   48,   61,
   48,  177,  158,   64,  138,  180,    1,  100,  113,   32,
   32,   24,  108,   28,   25,  118,    7,   94,   31,    7,
   32,   32,   53,   32,  163,   62,   63,   48,  152,  168,
   32,  160,  107,   62,   63,  159,   88,  139,   33,   25,
  178,  169,   34,   62,   63,  116,  175,   25,  142,  118,
  139,   35,   36,   37,   38,   39,    1,  144,   82,   83,
   84,  152,  108,  100,   31,  118,   32,   25,  108,  173,
   81,   81,   81,   81,   81,   81,   94,   62,   63,    3,
  150,  151,  107,  133,  134,  135,   49,  136,  107,  139,
   26,  154,   26,   20,   26,   53,  118,   35,   36,   37,
   38,   39,    1,   90,   91,    4,  164,   26,   26,    4,
   71,  161,  162,   67,   68,   69,   70,   71,   72,   26,
   51,   26,   22,  144,   73,   34,  167,  176,  108,  144,
   49,  179,  172,  144,  108,  165,   51,    8,  108,    8,
    8,   72,    8,    8,    8,    8,   73,   34,  107,   62,
   63,  123,  124,   49,  107,  131,  132,    6,  107,  149,
  114,  115,  170,    8,  147,  145,   95,    8,   96,   97,
  155,   98,   31,    9,   32,  166,    8,    8,    8,    8,
    8,    8,  157,    0,   10,   11,   12,   13,   14,   15,
    0,    0,   33,    0,    0,    0,   34,    0,    0,    0,
   54,    0,   54,    0,   54,   35,   36,   37,   38,   39,
    1,   54,   54,   54,   54,   54,   54,   54,   54,    0,
   54,   54,   54,   54,   54,   54,   54,   54,   47,   54,
   47,   54,   47,  125,  126,  127,  128,  129,  130,   47,
   47,   47,   47,   47,   47,   47,   47,    0,    0,   54,
   47,   47,   47,   47,   47,   47,    0,   47,    0,   47,
   54,   54,   54,   54,   54,   54,   54,   54,    0,   54,
   54,   54,   54,   54,   54,   54,   54,   41,   54,   41,
   54,   41,    0,    0,    0,    0,    0,    0,   41,   41,
   41,   41,   41,   41,   41,   41,    0,    0,    0,   41,
   41,   41,   41,   41,    0,   35,   41,   35,   41,   35,
    0,    0,    0,    0,    0,    0,   35,   35,   35,   35,
   35,   35,   35,   35,    0,    0,    0,   35,   35,   33,
    0,   33,    0,   33,   35,    0,   35,    0,    0,    0,
   33,   33,   33,   33,   33,   33,   33,   33,    0,    0,
    0,   33,   33,   34,    0,   34,    0,   34,   33,    0,
   33,    0,    0,    0,   34,   34,   34,   34,   34,   34,
   34,   34,    0,    0,    0,   34,   34,   27,    0,   27,
    0,   27,   34,   28,   34,   28,   29,   28,   29,    0,
   29,    0,    0,    0,   27,   27,    0,    0,    0,    0,
   28,   28,    0,   29,   29,   30,   27,   30,   27,   30,
    0,    0,   28,    0,   28,   29,    0,   29,    0,    0,
    0,    0,   30,   30,   31,    0,   31,    0,   31,    0,
    0,    0,    0,    0,   30,    0,   30,    0,    0,    0,
    0,   31,   31,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,   31,    0,   31,
};
short yycheck[] = {                                      16,
    0,   26,    8,  109,    4,  120,   26,   42,   94,  105,
  265,  264,  264,  266,  266,  168,  268,   23,  266,   30,
  268,  174,  137,   40,  110,  178,  301,   52,   53,  281,
  282,  292,   52,  267,  295,   60,  294,   48,  263,  294,
  265,  293,  295,  295,  150,  281,  282,  295,  266,  164,
  265,  147,   52,  281,  282,  141,  291,  293,  283,  295,
  175,  167,  287,  281,  282,  268,  172,  295,  264,   94,
  293,  296,  297,  298,  299,  300,  301,  102,  288,  289,
  290,  266,  102,  108,  263,  110,  265,  295,  108,  261,
  125,  126,  127,  128,  129,  130,  107,  281,  282,    0,
  111,  112,  102,   85,   86,   87,  268,   89,  108,  293,
  264,  117,  266,  264,  268,  264,  141,  296,  297,  298,
  299,  300,  301,  284,  285,    0,  151,  281,  282,    4,
  266,  148,  149,  275,  276,  277,  278,  279,  280,  293,
  266,  295,  264,  168,  286,  287,  163,  174,  168,  174,
  295,  178,  169,  178,  174,  155,  295,  257,  178,  259,
  260,  266,  262,  263,  264,  265,  286,  287,  168,  281,
  282,   65,   66,  266,  174,   80,   81,    4,  178,  110,
   54,   55,  168,  283,  108,  102,  257,  287,  259,  260,
  119,  262,  263,  258,  265,  157,  296,  297,  298,  299,
  300,  301,  122,   -1,  269,  270,  271,  272,  273,  274,
   -1,   -1,  283,   -1,   -1,   -1,  287,   -1,   -1,   -1,
  264,   -1,  266,   -1,  268,  296,  297,  298,  299,  300,
  301,  275,  276,  277,  278,  279,  280,  281,  282,   -1,
  284,  285,  286,  287,  288,  289,  290,  291,  264,  293,
  266,  295,  268,   74,   75,   76,   77,   78,   79,  275,
  276,  277,  278,  279,  280,  281,  282,   -1,   -1,  264,
  286,  287,  288,  289,  290,  291,   -1,  293,   -1,  295,
  275,  276,  277,  278,  279,  280,  281,  282,   -1,  284,
  285,  286,  287,  288,  289,  290,  291,  264,  293,  266,
  295,  268,   -1,   -1,   -1,   -1,   -1,   -1,  275,  276,
  277,  278,  279,  280,  281,  282,   -1,   -1,   -1,  286,
  287,  288,  289,  290,   -1,  264,  293,  266,  295,  268,
   -1,   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,
  279,  280,  281,  282,   -1,   -1,   -1,  286,  287,  264,
   -1,  266,   -1,  268,  293,   -1,  295,   -1,   -1,   -1,
  275,  276,  277,  278,  279,  280,  281,  282,   -1,   -1,
   -1,  286,  287,  264,   -1,  266,   -1,  268,  293,   -1,
  295,   -1,   -1,   -1,  275,  276,  277,  278,  279,  280,
  281,  282,   -1,   -1,   -1,  286,  287,  264,   -1,  266,
   -1,  268,  293,  264,  295,  266,  264,  268,  266,   -1,
  268,   -1,   -1,   -1,  281,  282,   -1,   -1,   -1,   -1,
  281,  282,   -1,  281,  282,  264,  293,  266,  295,  268,
   -1,   -1,  293,   -1,  295,  293,   -1,  295,   -1,   -1,
   -1,   -1,  281,  282,  264,   -1,  266,   -1,  268,   -1,
   -1,   -1,   -1,   -1,  293,   -1,  295,   -1,   -1,   -1,
   -1,  281,  282,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,   -1,  293,   -1,  295,
};
#define YYFINAL 2
#ifndef YYDEBUG
#define YYDEBUG 0
#endif
#define YYMAXTOKEN 301
#if YYDEBUG
char *yyname[] = {
"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"TOKEN_PRINT","TOKEN_FUNCTION",
"TOKEN_FOR","TOKEN_IF","TOKEN_ELSE","TOKEN_RETURN","TOKEN_LEFT_BRACE",
"TOKEN_RIGHT_BRACE","TOKEN_LEFT_PAREN","TOKEN_RIGHT_PAREN","TOKEN_LEFT_BRACKET",
"TOKEN_RIGHT_BRACKET","TOKEN_STRING","TOKEN_INTEGER","TOKEN_CHAR","TOKEN_VOID",
"TOKEN_BOOLEAN","TOKEN_ARRAY","TOKEN_GE","TOKEN_LE","TOKEN_EQ","TOKEN_NE",
"TOKEN_LT","TOKEN_GT","TOKEN_AND","TOKEN_OR","TOKEN_NOT","TOKEN_INCREMENT",
"TOKEN_DECREMENT","TOKEN_ADD","TOKEN_SUBTRACT","TOKEN_MULTIPLY","TOKEN_DIVIDE",
"TOKEN_MODULUS","TOKEN_EXPONENTIATE","TOKEN_ASSIGN","TOKEN_COMMA","TOKEN_COLON",
"TOKEN_SEMICOLON","TOKEN_TRUE","TOKEN_FALSE","TOKEN_CHAR_LITERAL",
"TOKEN_INTEGER_LITERAL","TOKEN_STRING_LITERAL","TOKEN_IDENTIFIER",
};
char *yyrule[] = {
"$accept : program",
"program : decl_list",
"decl_list : decl decl_list",
"decl_list : decl",
"decl : identifier colon type assign expr semicolon",
"decl : identifier colon type semicolon",
"decl : identifier colon type assign left_brace stmt_list right_brace",
"stmt : open_stmt",
"stmt : closed_stmt",
"closed_stmt : decl",
"closed_stmt : expr semicolon",
"closed_stmt : return opt_expr semicolon",
"closed_stmt : print expr_list semicolon",
"closed_stmt : for left_paren opt_expr semicolon opt_expr semicolon opt_expr right_paren closed_stmt",
"closed_stmt : if left_paren expr right_paren closed_stmt else closed_stmt",
"closed_stmt : left_brace stmt_list right_brace",
"open_stmt : if left_paren expr right_paren stmt",
"open_stmt : if left_paren expr right_paren closed_stmt else open_stmt",
"open_stmt : for left_paren opt_expr semicolon opt_expr semicolon opt_expr right_paren open_stmt",
"stmt_list : not_empty_stmt_list",
"stmt_list :",
"not_empty_stmt_list : stmt not_empty_stmt_list",
"not_empty_stmt_list : stmt",
"expr : expr and compare_expr",
"expr : expr or compare_expr",
"expr : compare_expr",
"compare_expr : add_expr ne add_expr",
"compare_expr : add_expr gt add_expr",
"compare_expr : add_expr ge add_expr",
"compare_expr : add_expr lt add_expr",
"compare_expr : add_expr le add_expr",
"compare_expr : add_expr eq add_expr",
"compare_expr : add_expr",
"add_expr : add_expr add mul_expr",
"add_expr : add_expr subtract mul_expr",
"add_expr : mul_expr",
"mul_expr : mul_expr multiply expon_expr",
"mul_expr : mul_expr divide expon_expr",
"mul_expr : mul_expr modulus expon_expr",
"mul_expr : expon_expr",
"expon_expr : neg_expr exponentiate expon_expr",
"expon_expr : neg_expr",
"neg_expr : subtract incr_expr",
"neg_expr : not incr_expr",
"neg_expr : incr_expr",
"incr_expr : primary_expr increment",
"incr_expr : primary_expr decrement",
"incr_expr : primary_expr",
"opt_expr : expr",
"opt_expr :",
"expr_list : not_empty_expr_list",
"expr_list :",
"not_empty_expr_list : expr comma not_empty_expr_list",
"not_empty_expr_list : expr",
"primary_expr : identifier",
"primary_expr : identifier left_paren expr_list right_paren",
"primary_expr : integer_literal",
"primary_expr : string_literal",
"primary_expr : char_literal",
"primary_expr : true",
"primary_expr : false",
"primary_expr : left_paren expr right_paren",
"primary_expr : left_brace not_empty_expr_list right_brace",
"type : integer",
"type : void",
"type : string",
"type : char",
"type : boolean",
"type : array left_bracket opt_expr right_bracket type",
"type : function type left_paren param_list right_paren",
"param_list : not_empty_param_list",
"param_list :",
"not_empty_param_list : param",
"not_empty_param_list : param comma not_empty_param_list",
"param : type colon identifier",
"print : TOKEN_PRINT",
"function : TOKEN_FUNCTION",
"for : TOKEN_FOR",
"if : TOKEN_IF",
"else : TOKEN_ELSE",
"return : TOKEN_RETURN",
"left_brace : TOKEN_LEFT_BRACE",
"right_brace : TOKEN_RIGHT_BRACE",
"left_paren : TOKEN_LEFT_PAREN",
"right_paren : TOKEN_RIGHT_PAREN",
"left_bracket : TOKEN_LEFT_BRACKET",
"right_bracket : TOKEN_RIGHT_BRACKET",
"string : TOKEN_STRING",
"integer : TOKEN_INTEGER",
"char : TOKEN_CHAR",
"void : TOKEN_VOID",
"boolean : TOKEN_BOOLEAN",
"array : TOKEN_ARRAY",
"ge : TOKEN_GE",
"le : TOKEN_LE",
"eq : TOKEN_EQ",
"ne : TOKEN_NE",
"lt : TOKEN_LT",
"gt : TOKEN_GT",
"and : TOKEN_AND",
"or : TOKEN_OR",
"not : TOKEN_NOT",
"increment : TOKEN_INCREMENT",
"decrement : TOKEN_DECREMENT",
"add : TOKEN_ADD",
"subtract : TOKEN_SUBTRACT",
"multiply : TOKEN_MULTIPLY",
"divide : TOKEN_DIVIDE",
"modulus : TOKEN_MODULUS",
"exponentiate : TOKEN_EXPONENTIATE",
"assign : TOKEN_ASSIGN",
"comma : TOKEN_COMMA",
"colon : TOKEN_COLON",
"semicolon : TOKEN_SEMICOLON",
"true : TOKEN_TRUE",
"false : TOKEN_FALSE",
"char_literal : TOKEN_CHAR_LITERAL",
"integer_literal : TOKEN_INTEGER_LITERAL",
"string_literal : TOKEN_STRING_LITERAL",
"identifier : TOKEN_IDENTIFIER",
};
#endif
#if YYDEBUG
#include <stdio.h>
#endif

/* define the initial stack-sizes */
#ifdef YYSTACKSIZE
#undef YYMAXDEPTH
#define YYMAXDEPTH  YYSTACKSIZE
#else
#ifdef YYMAXDEPTH
#define YYSTACKSIZE YYMAXDEPTH
#else
#define YYSTACKSIZE 10000
#define YYMAXDEPTH  10000
#endif
#endif

#define YYINITSTACKSIZE 500

int      yydebug;
int      yynerrs;
int      yyerrflag;
int      yychar;
short   *yyssp;
YYSTYPE *yyvsp;
YYSTYPE  yyval;
YYSTYPE  yylval;

/* variables for the parser stack */
static short   *yyss;
static short   *yysslim;
static YYSTYPE *yyvs;
static int      yystacksize;
#line 421 "parser.y"

int yyerror(char *str) {
	printf("yytext: %s\n",yytext);
	printf("parse error: %s\n",str);
	return 1;
}
#line 496 "parser.tab.c"
/* allocate initial stack or double stack size, up to YYMAXDEPTH */
static int yygrowstack(void)
{
    int newsize, i;
    short *newss;
    YYSTYPE *newvs;

    if ((newsize = yystacksize) == 0)
        newsize = YYINITSTACKSIZE;
    else if (newsize >= YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > YYMAXDEPTH)
        newsize = YYMAXDEPTH;

    i = yyssp - yyss;
    newss = (yyss != 0)
          ? (short *)realloc(yyss, newsize * sizeof(*newss))
          : (short *)malloc(newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    yyss  = newss;
    yyssp = newss + i;
    newvs = (yyvs != 0)
          ? (YYSTYPE *)realloc(yyvs, newsize * sizeof(*newvs))
          : (YYSTYPE *)malloc(newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    yyvs = newvs;
    yyvsp = newvs + i;
    yystacksize = newsize;
    yysslim = yyss + newsize - 1;
    return 0;
}

#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
int
yyparse(void)
{
    register int yym, yyn, yystate;
#if YYDEBUG
    register const char *yys;

    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif

    yynerrs = 0;
    yyerrflag = 0;
    yychar = YYEMPTY;

    if (yyss == NULL && yygrowstack()) goto yyoverflow;
    yyssp = yyss;
    yyvsp = yyvs;
    *yyssp = yystate = 0;

yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yyssp >= yysslim && yygrowstack())
        {
            goto yyoverflow;
        }
        *++yyssp = yystate = yytable[yyn];
        *++yyvsp = yylval;
        yychar = YYEMPTY;
        if (yyerrflag > 0)  --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;

    yyerror("syntax error");

#ifdef lint
    goto yyerrlab;
#endif

yyerrlab:
    ++yynerrs;

yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yyssp]) && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yyssp, yytable[yyn]);
#endif
                if (yyssp >= yysslim && yygrowstack())
                {
                    goto yyoverflow;
                }
                *++yyssp = yystate = yytable[yyn];
                *++yyvsp = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yyssp);
#endif
                if (yyssp <= yyss) goto yyabort;
                --yyssp;
                --yyvsp;
            }
        }
    }
    else
    {
        if (yychar == 0) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = YYEMPTY;
        goto yyloop;
    }

yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    if (yym)
        yyval = yyvsp[1-yym];
    else
        memset(&yyval, 0, sizeof yyval);
    switch (yyn)
    {
case 1:
#line 91 "parser.y"
{
	yyval.decl = yyvsp[0].decl;
	parser_result = yyvsp[0].decl;
	return 0;
}
break;
case 2:
#line 98 "parser.y"
{
	yyvsp[-1].decl -> next = yyvsp[0].decl;
	yyval.decl = yyvsp[-1].decl;
}
break;
case 3:
#line 102 "parser.y"
{
	yyval.decl = yyvsp[0].decl;
}
break;
case 4:
#line 107 "parser.y"
{
	yyval.decl = decl_create(yyvsp[-5].name,yyvsp[-3].type,yyvsp[-1].expr,0,0);
}
break;
case 5:
#line 110 "parser.y"
{
	yyval.decl = decl_create(yyvsp[-3].name,yyvsp[-1].type,0,0,0);
}
break;
case 6:
#line 113 "parser.y"
{
	yyval.decl = decl_create(yyvsp[-6].name,yyvsp[-4].type,0,yyvsp[-1].stmt,0);
}
break;
case 7:
#line 118 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 8:
#line 121 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 9:
#line 126 "parser.y"
{
	yyval.stmt = stmt_create(STMT_DECL,yyvsp[0].decl,0,0,0,0,0);
}
break;
case 10:
#line 129 "parser.y"
{
	yyval.stmt = stmt_create(STMT_EXPR,0,0,yyvsp[-1].expr,0,0,0);
}
break;
case 11:
#line 132 "parser.y"
{
	yyval.stmt = stmt_create(STMT_RETURN,0,0,yyvsp[-1].expr,0,0,0);
}
break;
case 12:
#line 135 "parser.y"
{
	yyval.stmt = stmt_create(STMT_PRINT,0,0,yyvsp[-1].expr,0,0,0);
}
break;
case 13:
#line 138 "parser.y"
{
	yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);
}
break;
case 14:
#line 141 "parser.y"
{
	yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);
}
break;
case 15:
#line 144 "parser.y"
{
	yyval.stmt = stmt_create(STMT_BLOCK,0,0,0,0,0,yyvsp[-1].stmt);
}
break;
case 16:
#line 149 "parser.y"
{
	yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-2].expr,0,yyvsp[0].stmt,0);
}
break;
case 17:
#line 152 "parser.y"
{
	yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);
}
break;
case 18:
#line 155 "parser.y"
{
	yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);
}
break;
case 19:
#line 160 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 20:
#line 163 "parser.y"
{
}
break;
case 21:
#line 167 "parser.y"
{
	yyvsp[-1].stmt -> next = yyvsp[0].stmt;
	yyval.stmt = yyvsp[-1].stmt;
}
break;
case 22:
#line 171 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 23:
#line 176 "parser.y"
{
	yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 24:
#line 179 "parser.y"
{
	yyval.expr = expr_create(EXPR_OR,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 25:
#line 182 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 26:
#line 187 "parser.y"
{
	yyval.expr = expr_create(EXPR_NE,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 27:
#line 190 "parser.y"
{
	yyval.expr = expr_create(EXPR_GT,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 28:
#line 193 "parser.y"
{
	yyval.expr = expr_create(EXPR_GE,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 29:
#line 196 "parser.y"
{
	yyval.expr = expr_create(EXPR_LT,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 30:
#line 199 "parser.y"
{
	yyval.expr = expr_create(EXPR_LE,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 31:
#line 202 "parser.y"
{
	yyval.expr = expr_create(EXPR_EQ,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 32:
#line 205 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 33:
#line 210 "parser.y"
{
	yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 34:
#line 213 "parser.y"
{
	yyval.expr = expr_create(EXPR_SUB,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 35:
#line 216 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 36:
#line 221 "parser.y"
{
	yyval.expr = expr_create(EXPR_MUL,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 37:
#line 224 "parser.y"
{
	yyval.expr = expr_create(EXPR_DIV,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 38:
#line 227 "parser.y"
{
	yyval.expr = expr_create(EXPR_MOD,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 39:
#line 230 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 40:
#line 235 "parser.y"
{
	yyval.expr = expr_create(EXPR_EXPON,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 41:
#line 238 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 42:
#line 243 "parser.y"
{
	yyval.expr = expr_create(EXPR_NEG,yyvsp[0].expr,0);
}
break;
case 43:
#line 246 "parser.y"
{
	yyval.expr = expr_create(EXPR_NOT,yyvsp[0].expr,0);
}
break;
case 44:
#line 249 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 45:
#line 254 "parser.y"
{
	yyval.expr = expr_create(EXPR_INCR,yyvsp[-1].expr,0);
}
break;
case 46:
#line 257 "parser.y"
{
	yyval.expr = expr_create(EXPR_DECR,yyvsp[-1].expr,0);
}
break;
case 47:
#line 260 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 48:
#line 265 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 49:
#line 268 "parser.y"
{
}
break;
case 50:
#line 272 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 51:
#line 275 "parser.y"
{
}
break;
case 52:
#line 279 "parser.y"
{
	yyval.expr = expr_create(EXPR_LIST,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 53:
#line 282 "parser.y"
{
	yyval.expr = expr_create(EXPR_LIST,yyvsp[0].expr,0);
}
break;
case 54:
#line 287 "parser.y"
{
	yyval.expr = expr_create_name(yyvsp[0].name);
}
break;
case 55:
#line 290 "parser.y"
{
	struct expr *id = expr_create_name(yyvsp[-3].name);
	yyval.expr = expr_create(EXPR_FUNC,id,yyvsp[-1].expr);
}
break;
case 56:
#line 294 "parser.y"
{
	yyval.expr = expr_create_integer_literal(yyvsp[0].integer);
}
break;
case 57:
#line 297 "parser.y"
{
	yyval.expr = expr_create_string_literal(yyvsp[0].name);
}
break;
case 58:
#line 300 "parser.y"
{
	yyval.expr = expr_create_character_literal(yyvsp[0].integer);
}
break;
case 59:
#line 303 "parser.y"
{
	yyval.expr = expr_create_boolean_literal(1);
}
break;
case 60:
#line 306 "parser.y"
{
	yyval.expr = expr_create_boolean_literal(0);
}
break;
case 61:
#line 309 "parser.y"
{
	yyval.expr = yyvsp[-1].expr;
}
break;
case 62:
#line 312 "parser.y"
{
	yyval.expr = yyvsp[-1].expr;
}
break;
case 63:
#line 317 "parser.y"
{
	yyval.type = type_create(TYPE_INTEGER,0,0);
}
break;
case 64:
#line 320 "parser.y"
{
	yyval.type = type_create(TYPE_VOID,0,0);
}
break;
case 65:
#line 323 "parser.y"
{
	yyval.type = type_create(TYPE_STRING,0,0);
}
break;
case 66:
#line 326 "parser.y"
{
	yyval.type = type_create(TYPE_CHARACTER,0,0);
}
break;
case 67:
#line 329 "parser.y"
{
	yyval.type = type_create(TYPE_BOOLEAN,0,0);
}
break;
case 68:
#line 332 "parser.y"
{
	yyval.type = type_create(TYPE_ARRAY,0,yyvsp[0].type);
}
break;
case 69:
#line 335 "parser.y"
{
	yyval.type = type_create(TYPE_FUNCTION,yyvsp[-1].param_list,yyvsp[-3].type);
}
break;
case 70:
#line 340 "parser.y"
{
	yyval.param_list = yyvsp[0].param_list;
}
break;
case 71:
#line 343 "parser.y"
{
}
break;
case 72:
#line 347 "parser.y"
{
	yyval.param_list = yyvsp[0].param_list;
}
break;
case 73:
#line 350 "parser.y"
{
	yyvsp[-2].param_list -> next = yyvsp[0].param_list;
	yyval.param_list = yyvsp[-2].param_list;
}
break;
case 74:
#line 356 "parser.y"
{
	yyval.param_list = param_list_create(yyvsp[0].name,yyvsp[-2].type,0);
}
break;
case 116:
#line 403 "parser.y"
{
	yyval.integer = yytext[0];
}
break;
case 117:
#line 406 "parser.y"
{
	yyval.integer = atoi(yytext);
}
break;
case 118:
#line 409 "parser.y"
{
	char *str = malloc(sizeof(char) * 256);
	strcpy(str,yytext);
	yyval.name = str;
}
break;
case 119:
#line 414 "parser.y"
{
	char *id = malloc(sizeof(char) * 256);
	strcpy(id,yytext);
	yyval.name = id;
}
break;
#line 1151 "parser.tab.c"
    }
    yyssp -= yym;
    yystate = *yyssp;
    yyvsp -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yyssp = YYFINAL;
        *++yyvsp = yyval;
        if (yychar < 0)
        {
            if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
            if (yydebug)
            {
                yys = 0;
                if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
                if (!yys) yys = "illegal-symbol";
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == 0) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yyssp, yystate);
#endif
    if (yyssp >= yysslim && yygrowstack())
    {
        goto yyoverflow;
    }
    *++yyssp = yystate;
    *++yyvsp = yyval;
    goto yyloop;

yyoverflow:
    yyerror("yacc stack overflow");

yyabort:
    return (1);

yyaccept:
    return (0);
}
